### ISSUE TITLE
RWS Sites 9.6 - Deployer Startup Error

### ISSUE THREAD

**Issue by tomsdept** [SI4T/SI4T#28]
Do the SI4T/SOLR jars need updating for RWS Sites 9.6 or is this error something else? Can anyone confirm? I'm currently seeing the following error when starting up our deployer. The deployer starts up fine without SI4T Configuration / Libs.

```
2022-10-21 09:37:14,930 INFO  GenericAddonServiceApi - Add-on resource stored in: /sdl-service/extensions/deployer-web.zip
--
2022-10-21 09:37:14,931 INFO  ExtensionInstaller - Installing: 1 extensions
2022-10-21 09:37:14,931 INFO  ExtensionInstaller - Installing extension from zip: extensions/deployer-web.zip
2022-10-21 09:37:14,931 INFO  ExtensionInstaller - Using folder name: deployer-web
2022-10-21 09:37:14,931 INFO  ExtensionInstaller - Storing extension in path: extensions/deployer-web
2022-10-21 09:37:15,093 INFO  ServiceContainer - Licensed CPU consumption for service: 1
2022-10-21 09:37:15,096 INFO  ServiceContainer - Activating extensions before application creation
2022-10-21 09:37:16,001 ERROR ServiceContainer - Could not start ServiceContainer
java.lang.reflect.InvocationTargetException: null
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at com.sdl.delivery.service.ServiceContainer.extensionInitialize(ServiceContainer.java:128)
at com.sdl.delivery.service.ServiceContainer.main(ServiceContainer.java:97)
Caused by: java.lang.NoSuchMethodError: 'void org.apache.http.impl.conn.CPool.setValidateAfterInactivity(int)'
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:183)
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:165)
at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:984)
at org.apache.http.impl.client.HttpClients.createSystem(HttpClients.java:64)
at org.springframework.http.client.HttpComponentsClientHttpRequestFactory.<init>(HttpComponentsClientHttpRequestFactory.java:75)
at com.sdl.delivery.addon.client.ApiClient.buildRestTemplate(ApiClient.java:399)
at com.sdl.delivery.addon.client.ApiClient.<init>(ApiClient.java:111)
at com.sdl.delivery.addon.client.api.AddonClientFacade.<init>(AddonClientFacade.java:94)
at com.sdl.delivery.addon.client.api.AddonClientFacadeProvider.<init>(AddonClientFacadeProvider.java:12)
at com.sdl.delivery.addon.client.api.AddonClientFacadeProvider.<clinit>(AddonClientFacadeProvider.java:10)
at com.sdl.delivery.service.extension.ExtensionLoaderImpl.<init>(ExtensionLoaderImpl.java:39)
... 6 common frames omitted
```
>

**Comment by RaimondKempees** [comment]
Unsure. SI4T Solr ships now with http client 4.5.6 and the method for sure is there. Tridion 9.6 ships with a later version (> 4.5.12) and there the method is gone. 

Can you put the SI4T jars in, except httpclient-4.5.6.jar and see what happens?

**Comment by tomsdept** [comment]
Hi @RaimondKempees Thanks for the quick reply, will give this a go! Will report back

**Comment by tomsdept** [comment]
Hi @RaimondKempees startup is now fixed via removing `httpcore-4.4.13.jar` but now getting a deploy error on publish. Thanks for your help so far.

```
2022-10-21 12:21:10,694 INFO  TridionExecutableStepFactory - Waiting 500 ms for being initialized.
2022-10-21 12:21:10,697 INFO  TridionExecutableStepFactory - Initialized executable step BinaryDeploy using TridionExecutableStepFactory factory
2022-10-21 12:21:10,897 INFO  TridionExecutableStepFactory - Waiting 500 ms for being initialized.
2022-10-21 12:21:10,898 INFO  TridionExecutableStepFactory - Initialized executable step ComponentDeploy using TridionExecutableStepFactory factory
2022-10-21 12:21:11,667 INFO  TridionExecutableStepFactory - Waiting 500 ms for being initialized.
2022-10-21 12:21:11,668 INFO  TridionExecutableStepFactory - Initialized executable step TemplateDeploy using TridionExecutableStepFactory factory
2022-10-21 12:21:11,763 INFO  TridionExecutableStepFactory - Waiting 500 ms for being initialized.
2022-10-21 12:21:11,764 INFO  TridionExecutableStepFactory - Initialized executable step PublicationDeploy using TridionExecutableStepFactory factory
2022-10-21 12:21:11,855 INFO  TridionExecutableStepFactory - Waiting 500 ms for being initialized.
2022-10-21 12:21:11,859 INFO  TridionExecutableStepFactory - Initialized executable step TaxonomyDeploy using TridionExecutableStepFactory factory
2022-10-21 12:21:11,971 INFO  TridionExecutableStepFactory - Waiting 500 ms for being initialized.
2022-10-21 12:21:11,977 INFO  TridionExecutableStepFactory - Initialized executable step ComponentPresentationDeploy using TridionExecutableStepFactory factory
2022-10-21 12:21:12,076 INFO  TridionExecutableStepFactory - Waiting 500 ms for being initialized.
2022-10-21 12:21:12,078 INFO  TridionExecutableStepFactory - Initialized executable step StructureGroupDeploy using TridionExecutableStepFactory factory
2022-10-21 12:21:12,169 INFO  SpringAwareExecutableStepFactory - Initialized executable step TridionContentDataStep using SpringAwareExecutableStepFactory factory
2022-10-21 12:21:12,304 INFO  TridionSearchIndexDeployStep - Indexing step configured but search profile is not active. Skipping all Indexing steps
2022-10-21 12:21:12,304 INFO  SpringAwareExecutableStepFactory - Initialized executable step TridionSearchIndexDeployStep using SpringAwareExecutableStepFactory factory
2022-10-21 12:21:12,388 INFO  SpringAwareExecutableStepFactory - Initialized executable step TridionPreCommitStep using SpringAwareExecutableStepFactory factory
2022-10-21 12:21:12,470 INFO  TransactionManagerImpl - Starting storage transaction: tcm:0-1253116-66560
2022-10-21 12:21:12,912 INFO  JPASearchBinaryContentDAO - Checking update for: /media/redacted.jpg
2022-10-21 12:21:13,076 INFO  JPASearchBinaryContentDAO - Checking update for: /media/redacted.svg
2022-10-21 12:21:13,181 INFO  TaxonomyService - Keyword count set to: false for taxonomies
2022-10-21 12:21:13,275 INFO  TridionPublishableItemProcessor - Finding search directives.
2022-10-21 12:21:13,278 INFO  SearchIndexProcessor - Registering tcm:9-868-64, for: UPDATE
2022-10-21 12:21:13,616 INFO  SpringAwareExecutableStepFactory - Initialized executable step TridionCommitStep using SpringAwareExecutableStepFactory factory
2022-10-21 12:21:13,656 INFO  TransactionManagerImpl - Starting storage transaction: tcm:0-1253116-66560
2022-10-21 12:21:13,656 INFO  TransactionManagerImpl - Committing storage transaction: tcm:0-1253116-66560
2022-10-21 12:21:13,656 INFO  JPASearchDAOFactory - Start committing transaction: tcm:0-1253116-66560
2022-10-21 12:21:13,659 INFO  SearchIndexProcessor - Triggering Indexing for transaction: tcm:0-1253116-66560
2022-10-21 12:21:13,659 INFO  SearchIndexProcessor - Indexing was requested for Storage Id: defaultdb
2022-10-21 12:21:13,660 INFO  SolrIndexer - No Solr Url found for publication Id: 9. Trying to use the DefaultCoreUrl
2022-10-21 12:21:13,660 INFO  SolrIndexer - Default Url found. Using [http://REDACTED:8983/solr/REDACTED/] to connect to.
2022-10-21 12:21:13,660 INFO  SolrIndexer - Adding pages and component presentations to Solr in batches of 10
2022-10-21 12:21:13,662 ERROR SolrIndexer - Unexpected exception: 'void org.apache.solr.common.SolrInputDocument.<init>(java.lang.String[])'
java.lang.NoSuchMethodError: 'void org.apache.solr.common.SolrInputDocument.<init>(java.lang.String[])'
	at org.si4t.solr.SolrIndexer.constructInputDocument(SolrIndexer.java:362)
	at org.si4t.solr.SolrIndexer.commitAddContentToSolr(SolrIndexer.java:339)
	at org.si4t.solr.SolrIndexer.processItemUpdates(SolrIndexer.java:308)
	at org.si4t.solr.SolrIndexer.commit(SolrIndexer.java:257)
	at com.tridion.storage.si4t.SearchIndexProcessor.triggerIndexing(SearchIndexProcessor.java:231)
	at com.tridion.storage.si4t.JPASearchDAOFactory.commitTransaction(JPASearchDAOFactory.java:188)
	at com.tridion.storage.management.TransactionManagerImpl.commitTransaction(TransactionManagerImpl.java:65)
	at com.tridion.storage.StorageManagerFactory.commitTransaction(StorageManagerFactory.java:394)
	at com.sdl.delivery.deployer.steps.TridionTransactionalExecutableStep.commitTransaction(TridionTransactionalExecutableStep.java:78)
	at com.sdl.delivery.deployer.steps.TridionCommitStep.process(TridionCommitStep.java:28)
	at com.sdl.delivery.deployer.engine.pipeline.actor.StepActor.execute(StepActor.scala:73)
	at com.sdl.delivery.deployer.engine.pipeline.actor.StepActor.com$sdl$delivery$deployer$engine$pipeline$actor$StepActor$$processStep(StepActor.scala:58)
	at com.sdl.delivery.deployer.engine.pipeline.actor.StepActor$$anonfun$receive$1.applyOrElse(StepActor.scala:41)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at com.sdl.delivery.deployer.engine.pipeline.actor.StepActor.aroundReceive(StepActor.scala:27)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:614)
	at akka.actor.ActorCell.invoke(ActorCell.scala:583)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-10-21 12:21:13,663 INFO  SolrIndexer - Clearing out registers.
2022-10-21 12:21:13,663 ERROR JPASearchDAOFactory - Unexpected exception:'void org.apache.solr.common.SolrInputDocument.<init>(java.lang.String[])'
com.tridion.storage.si4t.IndexingException: Unexpected exception:'void org.apache.solr.common.SolrInputDocument.<init>(java.lang.String[])'
	at org.si4t.solr.SolrIndexer.commit(SolrIndexer.java:275)
	at com.tridion.storage.si4t.SearchIndexProcessor.triggerIndexing(SearchIndexProcessor.java:231)
	at com.tridion.storage.si4t.JPASearchDAOFactory.commitTransaction(JPASearchDAOFactory.java:188)
	at com.tridion.storage.management.TransactionManagerImpl.commitTransaction(TransactionManagerImpl.java:65)
	at com.tridion.storage.StorageManagerFactory.commitTransaction(StorageManagerFactory.java:394)
	at com.sdl.delivery.deployer.steps.TridionTransactionalExecutableStep.commitTransaction(TridionTransactionalExecutableStep.java:78)
	at com.sdl.delivery.deployer.steps.TridionCommitStep.process(TridionCommitStep.java:28)
	at com.sdl.delivery.deployer.engine.pipeline.actor.StepActor.execute(StepActor.scala:73)
	at com.sdl.delivery.deployer.engine.pipeline.actor.StepActor.com$sdl$delivery$deployer$engine$pipeline$actor$StepActor$$processStep(StepActor.scala:58)
	at com.sdl.delivery.deployer.engine.pipeline.actor.StepActor$$anonfun$receive$1.applyOrElse(StepActor.scala:41)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at com.sdl.delivery.deployer.engine.pipeline.actor.StepActor.aroundReceive(StepActor.scala:27)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:614)
	at akka.actor.ActorCell.invoke(ActorCell.scala:583)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-10-21 12:21:13,663 INFO  SearchIndexProcessor - Cleared out transaction with transactionId: tcm:0-1253116-66560.
2022-10-21 12:21:13,663 INFO  TransactionManagerImpl - Commit failed: com.tridion.storage.si4t.IndexingException: Unexpected exception:'void org.apache.solr.common.SolrInputDocument.<init>(java.lang.String[])'
2022-10-21 12:21:13,664 ERROR TridionCommitStep - Commit failed for execution id:tcm:0-1253116-66560
com.sdl.delivery.deployer.api.processing.exception.ProcessingException: Unable to commit transactions. ExecutionId: tcm:0-1253116-66560. Error: Commit failed for transaction tcm:0-1253116-66560 because of com.tridion.storage.si4t.IndexingException: Unexpected exception:'void org.apache.solr.common.SolrInputDocument.<init>(java.lang.String[])'.
	at com.sdl.delivery.deployer.steps.TridionTransactionalExecutableStep.commitTransaction(TridionTransactionalExecutableStep.java:80)
	at com.sdl.delivery.deployer.steps.TridionCommitStep.process(TridionCommitStep.java:28)
	at com.sdl.delivery.deployer.engine.pipeline.actor.StepActor.execute(StepActor.scala:73)
	at com.sdl.delivery.deployer.engine.pipeline.actor.StepActor.com$sdl$delivery$deployer$engine$pipeline$actor$StepActor$$processStep(StepActor.scala:58)
	at com.sdl.delivery.deployer.engine.pipeline.actor.StepActor$$anonfun$receive$1.applyOrElse(StepActor.scala:41)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at com.sdl.delivery.deployer.engine.pipeline.actor.StepActor.aroundReceive(StepActor.scala:27)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:614)
	at akka.actor.ActorCell.invoke(ActorCell.scala:583)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.tridion.broker.StorageException: Commit failed for transaction tcm:0-1253116-66560 because of com.tridion.storage.si4t.IndexingException: Unexpected exception:'void org.apache.solr.common.SolrInputDocument.<init>(java.lang.String[])'
	at com.tridion.storage.management.TransactionManagerImpl.commitTransaction(TransactionManagerImpl.java:70)
	at com.tridion.storage.StorageManagerFactory.commitTransaction(StorageManagerFactory.java:394)
	at com.sdl.delivery.deployer.steps.TridionTransactionalExecutableStep.commitTransaction(TridionTransactionalExecutableStep.java:78)
	... 14 common frames omitted
Caused by: com.tridion.broker.StorageException: com.tridion.storage.si4t.IndexingException: Unexpected exception:'void org.apache.solr.common.SolrInputDocument.<init>(java.lang.String[])'
	at com.tridion.storage.si4t.JPASearchDAOFactory.commitTransaction(JPASearchDAOFactory.java:202)
	at com.tridion.storage.management.TransactionManagerImpl.commitTransaction(TransactionManagerImpl.java:65)
	... 16 common frames omitted
Caused by: com.tridion.storage.si4t.IndexingException: Unexpected exception:'void org.apache.solr.common.SolrInputDocument.<init>(java.lang.String[])'
	at org.si4t.solr.SolrIndexer.commit(SolrIndexer.java:275)
	at com.tridion.storage.si4t.SearchIndexProcessor.triggerIndexing(SearchIndexProcessor.java:231)
	at com.tridion.storage.si4t.JPASearchDAOFactory.commitTransaction(JPASearchDAOFactory.java:188)
	... 17 common frames omitted
```

**Comment by RaimondKempees** [comment]
I think you need to upgrade solrj to version 8.8.1. Can you try that?

**Comment by tomsdept** [comment]
@RaimondKempees Thats completely resolved it and now deploying perfectly! I really appreciate the help here, thanks!
